### ISSUE TITLE
Migration questions

### ISSUE THREAD

**Issue by rugk** [gcp/twitter-link-expander#2]
I came here from two other add-ons (https://github.com/idlewan/link_cleaner/issues/18), so I have a few questions:
* Other add-ons had big problems expanding the links in Twitter cards. Can this add-on finally do so?
* Is the full URL correctly shown on hover, or only when the short link is clicked?

Note that maybe the source code of the other add-ons can help. One also packaged their add-on as a userscript.

**Comment by gcp** [comment]
Twitter cards don't have the original link in them in the HTML so they can't be expanded without visiting them, which would defeat the purpose. Hovering works.

**Comment by rugk** [comment]
>Twitter cards don't have the original link in them in the HTML so they can't be expanded without visiting them, which would defeat the purpose.

Indeed, but without that feature the add-on is incomplete. Other add-on authors tried to just extract the link from the tweet, where the twittercard is embedded. This should be possible, theoretically…
