### ISSUE TITLE
Icon not shown in add-on overview

### ISSUE THREAD

**Issue by rugk** [gcp/twitter-link-expander#4]
The icon is not shown:

![grafik](https://user-images.githubusercontent.com/11966684/29910870-f8aeac18-8e2b-11e7-9a1d-056444fb6668.png)

Only when I click on the add-on entry it is shown.

Firefox 55

**Comment by gcp** [comment]
This is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1388705
